version: "3.8"
services:
  nats:
    image: 'nats:2.9'
    entrypoint: /nats-server
    command: --name nats --cluster_name nats_jetstream --js --sd /data  -p 4222 -m 8222
    volumes:
      - nats-data:/data
    ports:
      - 4222:4222
      - 8222:8222
volumes:
  nats-data:
